onlineapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from onlineapp.views import *
from django.conf.urls import url

app_name = 'onlineapp'

urlpatterns = [
    path('api/colleges/',CollegeListViewApi), #Gets all colleges
    path('api/colleges/add/',CreateCollegeViewApi), # creates college
    path('api/colleges/<int:id>/',CollegeViewApi), #Gets particular college
    path("api/colleges/update/<int:pk>", CollegeChangeViewApi), #Updates College
    path("api/colleges/delete/<int:pk>", CollegeChangeViewApi), #Deletes College
    path('api/colleges/<int:id>/students/',StudentsofCollegeViewApi.as_view()), #Gets all students of colleges
    path('api/colleges/<int:id>/studentsmarks/',StudentsMarksofCollegeViewApi.as_view()), #Gets marks of all students particular college
    path('api/colleges/<int:id>/students/<int:pk>/',StudentViewApi.as_view()), #Gets marks of particular student

    path('signup/',SignUpView.as_view(),name="signup"),
    path("login/",LoginView.as_view(),name="login"),
    path("logout",logout_user,name="logout"),
    path("colleges/",CollegeListView.as_view(),name="colleges_html"),
    path("colleges/<int:id>",CollegeDetailsView.as_view(),name="college_details"),
    path("colleges/add",CreateCollegeView.as_view(),name="college_form"),
    path("colleges/update/<int:pk>",UpdateCollegeView.as_view(),name="update_college"),
    path("colleges/delete/<int:pk>",DeleteCollegeView.as_view(),name="delete_college"),
    path("colleges/<int:id>/add",CreateStudentView.as_view(),name="student_form"),
    path("colleges/<int:id>/update/<int:pk>",UpdateStudentView.as_view(),name="update_student"),
    path("colleges/<str:acronym>",CollegeDetailsView.as_view(),name="college_details"),
    path("colleges/<int:id>/delete/<int:pk>",DeleteStudentView.as_view(),name="delete_student")
]

onlineproject/urls.py
from django.contrib import admin
from django.urls import path
from onlineapp.views import *
from django.conf import settings
from django.conf.urls import include, url
import debug_toolbar

urlpatterns=[
    url(r'^admin/',admin.site.urls),
    url(r'',include('onlineapp.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

onlineapp/models.py
from django.db import models

# Create your models here.
class College(models.Model):
    name = models.CharField(max_length=128)
    location=models.CharField(max_length=64)
    acronym=models.CharField(max_length=10)
    contact=models.EmailField(max_length=50)

    def __str__(self):
        return self.acronym

class Student(models.Model):
    name=models.CharField(max_length=128)
    dob=models.DateField(null=True,blank=True)
    email=models.EmailField(max_length=50)
    db_folder=models.CharField(max_length=50)
    dropped_out=models.BooleanField(default=False)

    college=models.ForeignKey(College,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class MockTest1(models.Model):
    problem1 = models.IntegerField()
    problem2 = models.IntegerField()
    problem3 = models.IntegerField()
    problem4 = models.IntegerField()
    total=models.IntegerField()

    student=models.OneToOneField(Student,on_delete=models.CASCADE)

    def __str__(self):
        return f"Student { self.student.name } marks"

onlineapp/forms/forms.py
from django import forms
from onlineapp.models import *

class AddCollege(forms.ModelForm):
    class Meta:
        model=College
        exclude=['id']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'College Name'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Location'}),
            'acronym': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Acronym'}),
            'contact': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Contact'}),
        }

class StudentForm(forms.ModelForm):
    class Meta:
        model=Student
        exclude=['id','dob','college']
        widgets={
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
            'db_folder':forms.TextInput(attrs={'class':'form-control','placeholder':'DB_Folder name'}),
            'dropped_out':forms.CheckboxInput(attrs={'class':'checkbox'}),
        }


class MockTest1Form(forms.ModelForm):
    class Meta:
        model=MockTest1
        exclude={'id','total','student'}
        widgets = {
            'problem1': forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'score in problem1'}),
            'problem2': forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'score in problem2'}),
            'problem3': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'score in problem3'}),
            'problem4': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'score in problem4'}),
            'problem4': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'score in problem4'}),
        }

onlineapp/views/college.py
from django.views import View
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from onlineapp.forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
import ipdb

class CollegeView(View):

    def get(self,request,*args,**kwargs):
        colleges=College.objects.all()
        return render(request,template_name='college.html',context={'colleges':colleges})


class CollegeListView(LoginRequiredMixin,ListView):
    login_url='/login/'

    model=College
    context_object_name='colleges'
    template_name = 'colleges.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super(CollegeListView,self).get_context_data(**kwargs)
        context['data']=self.model.objects.values('id','name','acronym')
        context.update({'user_permissions':self.request.user.get_all_permissions})
        return context


class CollegeDetailsView(LoginRequiredMixin,DetailView):
    login_url = '/login/'
    model = College
    template_name = 'collegedetails.html'
    def get_object(self,queryset=None):
        return get_object_or_404(College,**self.kwargs)


    def get_context_data(self,**kwargs):
        context=super(CollegeDetailsView,self).get_context_data(**kwargs)
        college=context.get('college')
        students=list(college.student_set.order_by("-mocktest1__total"))
        context.update({
            'students':students,
            'user_permissions':self.request.user.get_all_permissions()
        })
        return context


class CreateCollegeView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    permission_required = 'create_college'
    login_url = '/login/'
    model = College
    template_name = 'college_form.html'
    form_class = AddCollege
    success_url = reverse_lazy('onlineapp:colleges_html')


class UpdateCollegeView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    permission_required=('change_college')
    login_url = '/login/'
    model=College
    template_name="college_form.html"
    form_class=AddCollege
    success_url = reverse_lazy('onlineapp:colleges_html')

class DeleteCollegeView(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    permission_required = ('delete_college')
    login_url = '/login/'
    model=College
    template_name = "college_confirm_delete.html"
    success_url = reverse_lazy('onlineapp:colleges_html')

onlineapp/views/rest_college.py
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from onlineapp.models import *
from django.http import HttpResponse, JsonResponse
from onlineapp.serializers.model_serializers import *
from rest_framework.decorators import api_view,authentication_classes,permission_classes
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
import json

@api_view(['GET'])
@authentication_classes((BasicAuthentication,))
@permission_classes((IsAuthenticated,))
def CollegeListViewApi(request):
    if request.method == 'GET':
        colleges = College.objects.all()
        serializer = CollegeSerializer(colleges, many=True)
        return JsonResponse(serializer.data, safe=False)

@api_view(['POST'])
@authentication_classes((BasicAuthentication,))
@permission_classes((IsAuthenticated,))
def CreateCollegeViewApi(request):

    if request.method == 'POST':
        data=JSONParser().parse(request)
        serializer = CollegeSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

@api_view(['PUT','DELETE'])
@authentication_classes((BasicAuthentication,))
@permission_classes((IsAuthenticated,))
def CollegeChangeViewApi(request, pk):

    try:
        college = College.objects.get(pk=pk)
    except college.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'PUT':
        data=JSONParser().parse(request)
        serializer = CollegeSerializer(college, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        college.delete()
        return HttpResponse(status=204)


@api_view(['GET'])
@authentication_classes((BasicAuthentication,))
@permission_classes((IsAuthenticated,))
def CollegeViewApi(request,id):

    if request.method=='GET':
        college=College.objects.filter(pk=id)
        # import ipdb
        # ipdb.set_trace()
        serializer=CollegeSerializer(college,many=True)
        return JsonResponse(serializer.data,safe=False)

onlineapp/views/rest_student.py
from onlineapp.serializers.model_serializers import *
from rest_framework.decorators import api_view
from django.http import HttpResponse, JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated

# @api_view(['GET'])
# def StudentsOfCollegeViewApi(request,id):
#     if request.method=='GET':
#         college=College.objects.get(pk=id)
#         student=Student.objects.filter(college=college)
#         serializer=StudentSerializer(student,many=True)
#         return JsonResponse(serializer.data,safe=False)
#
# @api_view(['GET'])
# def StudentsMarksViewApi(request,id):
#     if request.method=='GET':
#         result=Student.objects.filter(college_id=id)
#         serializer=StudentDetailsSerializer(result,many=True)
#         return JsonResponse(serializer.data,safe=False)

class StudentsofCollegeViewApi(permissions.BasePermission,APIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self,request,id,format=None):
        result=Student.objects.filter(college_id=id)
        serializer=StudentSerializer(result,many=True)
        return Response(serializer.data)

    def post( self, request,id, format=None):
        import ipdb
        ipdb.set_trace()
        # print("hello world")
        serializer = StudentDetailsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class StudentsMarksofCollegeViewApi(APIView):

    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self,request,id,format=None):
        result=Student.objects.filter(college_id=id)
        serializer=StudentDetailsSerializer(result,many=True)
        return Response(serializer.data)

class StudentViewApi(APIView):

    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self,request,id,pk,format=None):
        result=Student.objects.filter(college_id=id,id=pk)
        serializer=StudentDetailsSerializer(result,many=True)
        return Response(serializer.data)

onlineapp/views/student.py
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from onlineapp.forms import *
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
import ipdb

class CreateMockTest1View(CreateView):
    model=MockTest1
    form_class=MockTest1Form

class CreateStudentView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    permission_required = 'create_student'
    login_url = '/login/'
    model = Student
    template_name = "student_form.html"
    form_class = StudentForm

    def get_context_data(self, **kwargs):
        context=super(CreateStudentView,self).get_context_data(**kwargs)
        student_form=context.get('form')
        test_form=MockTest1Form
        context.update({'student_form':student_form,'test_form':test_form})
        return context

    def post(self, request, *args, **kwargs):
        student_form=StudentForm(request.POST)
        test_form = MockTest1Form(request.POST)
        college=get_object_or_404(College,pk=kwargs.get('id'))

        if student_form.is_valid():
            new_student = student_form.save(commit=False)
            new_student.college=college
            new_student.save()

            if test_form.is_valid():
                new_student_marks=test_form.save(commit=False)
                new_student_marks.student=new_student
                new_student_marks.total=sum(test_form.cleaned_data.values())
                # ipdb.set_trace()
                new_student_marks.save()
        return redirect('onlineapp:college_details',**kwargs)

class UpdateStudentView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    permission_required = 'change_student'
    login_url = '/login/'
    model = Student
    template_name = "student_form.html"
    form_class = StudentForm

    def get_context_data(self, **kwargs):
        context=super(UpdateStudentView,self).get_context_data(**kwargs)
        student_form=context.get('student')
        test_form=MockTest1Form(instance=student_form.mocktest1)
        context.update({'student_form':context.get('form'),'test_form':test_form})
        return context

    def post(self, request, *args, **kwargs):
        college=get_object_or_404(College,pk=kwargs.get('id'))
        # student_instance = get_object_or_404(Student,pk=kwargs.get('pk'))
        # marks_instance = get_object_or_404(MockTest1,student_id=kwargs.get('pk'))
        student_instance=Student.objects.get(pk=kwargs.get('pk'))
        student_form=StudentForm(request.POST,instance=student_instance)
        test_form = MockTest1Form(request.POST,instance=student_instance.mocktest1)
        mocktest_form=test_form.save(commit=False)
        mocktest_form.total = sum(test_form.cleaned_data.values())
        student_form.save()
        mocktest_form.save()
        return redirect('onlineapp:college_details',id=kwargs.get("id"))

class DeleteStudentView(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    permission_required = 'delete_student'
    login_url = '/login/'
    model=Student
    success_url = reverse_lazy('onlineapp:colleges_html')

    def get(self,request,*args,**kwargs):
        return self.post(request,*args,**kwargs)

    def post(self,request,*args,**kwargs):
        self.delete(request,*args,**kwargs)
        return redirect('onlineapp:college_details',id=kwargs.get('id'))

onlineapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <title>{% block title %}College App{%endblock%}</title>
     <style>
        header{
            height:50px;
            font-size:30px;
        }
    </style>
</head>
<header class="bg-primary text-white">
    <div style="float:left">
    College App
    </div>

    <div style=" float:right">
        {% if request.user.is_authenticated%}
    <a style="color:white" href="{%url 'onlineapp:logout' %}" >Logout</a>
        {%endif%}
        </div>

</header>
{%block content %}
{% endblock %}
</html>

onlineapp/templates/college_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Confirmation</title>
</head>
<body class="container">
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</body>
</html>

onlineapp/templates/college_form.html
{% extends "base.html" %}
{% block title %}College Form{%endblock%}
{% block content %}
<body class="container">
<h1 style="color:green">
        College Form
</h1>
    <form   method="post">
        {%csrf_token%}
        {{form}}
        <br/>
        <input type="submit" class="btn btn-primary"value="submit">
    </form>
</body>

{%endblock%}

onlineapp/templates/collegedetails.html
{% extends "base.html" %}
{% block title %}Login{%endblock%}
{% block content %}
<body>
<h1 style="color:green">{{college.name}} College Details</h1>
{% if 'onlineapp.add_student' in user_permissions %}
<form action="{% url 'onlineapp:student_form' college.id %}">
        <input type="submit" value="Add Student" class="btn btn-success">
    </form>
{%endif%}
<br/>
<table class="table table-hover active">
    <tr>
        <th>Student ID</th>
        <th>Name</th>
        <th>Mocktest1 Total</th>
    </tr>
    {% for x in students %}
    <tr >
        <td>
            {{x.id}}
        </td>
        <td>
            {{x.name}}
        </td>
        <td>
            {{x.mocktest1.total}}
        </td>
        {% if 'onlineapp.change_student' in user_permissions %}
        <td><a href="{% url 'onlineapp:update_student' college.id  x.id %}">Edit</a></td>
        {%endif%}
        {% if 'onlineapp.delete_college' in user_permissions %}
        <td><a href="{% url 'onlineapp:delete_student' college.id  x.id %}">Delete</a></td>
        {%endif%}
    </tr>
    {% endfor %}
</table>
</body>
{%endblock%}

onlineapp/templates/colleges.html
{% extends "base.html" %}
{% block title %}Login{%endblock%}
{% block content %}
<body class="container">

<h1 style="color:green" >College Details</h1>
{% if 'onlineapp.add_college' in user_permissions %}
    <form  action="{% url 'onlineapp:college_form'%}">
        <input type="submit" value="Add" class="btn btn-success">
    </form>
{%endif%}

<br/>
<table class="table table-hover active">
    <tr>
        <th>
            College ID
        </th>
        <th>Name</th>
        <th>Acronym</th>
    </tr>
    {% for x in data %}
    <tr >
        <td>
            {{x.id}}
        </td>
        <td>
            <a href="{% url 'onlineapp:college_details' x.id %}">{{x.name}}</a>
        </td>
        <td>
            {{x.acronym}}
        </td>
        {% if 'onlineapp.change_college' in user_permissions %}
        <td><a href="{% url 'onlineapp:update_college' x.id %}">Edit</a></td>
        {%endif%}
        {% if 'onlineapp.delete_college' in user_permissions %}
        <td><a href="{% url 'onlineapp:delete_college' x.id %}">Delete</a></td>
        {%endif%}
    </tr>
    {% endfor %}
</table>
</body>
{%endblock%}

onlineapp/templates/loginform.html
{% extends "base.html" %}
{% block title %}Login{%endblock%}
{% block content %}
 <form class="container" method="post" >
        {%csrf_token%}
        {{form}}
        <br/>
        <input type="Submit" value="Login" class="btn btn-primary">
    </form>
 <div style="margin-left:600px">
    <a href="{% url 'onlineapp:signup' %}"> SignUp</a>
 </div>
{% endblock %}

onlineapp/templates/signupform.html
{% extends "base.html" %}
{% block title %}SignUp{%endblock%}
{% block content %}
<body >
 <form class="container" method="post" >
        {%csrf_token%}
        {{form}}
        <br/>
        <input type="Submit" value="SignUp" class="btn btn-primary">
    </form>
</body>
{%endblock%}

onlineapp/templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <style>
        body{
            text-align:center;
        }
        table{
            border:1px solid black;
            align-content: center;
            margin: auto;
        }
        td{
            border-left:1px solid black;
            border-bottom:1px solid black;
        }
        tr:nth-child(even){
            background-color: #f2f2f2;
        }
        td:hover{
        color:red;
        }
    </style>
</head>
<body>
<h1 style="color:cyan">Student Details</h1>
    <table>
        {%for s in sd%}
        <tr>
            <td>{{s.name}}</td>
            <td>{{s.email}}</td>
            <td>{{s.college__acronym}}</td>
        </tr>
        {%endfor%}
    </table>
</body>
</html>

onlineapp/templates/student_form.html
{% extends "base.html" %}
{% block title %}Add Student{%endblock%}
{% block content %}
<div class="container">
<h1 style="color:green">
        Student Form
</h1>
    <form method="post" >
        {%csrf_token%}
        {{student_form}}
        {{test_form}}
        <br/>
        <input type="Submit" value="Submit" class="btn btn-primary">
    </form>
</div>
{%endblock%}